#!/usr/bin/env bash

OS="$(uname -s)"
THIS_DIR="$(dirname "${0}")"

function print_help() {
cat <<-EOF
No prebuilt gn binary was found for this system.
Try building your own binary by doing:
  cd ~
  git clone https://github.com/DanCraft99/gn-standalone-mirror-2.git
  cd gn-standalone-mirror-2 && build/gen.py
  ninja -C out
Then cp out/gn to this folder
EOF
}

case "$OS" in
  Linux)
    MACHINE=$(uname -m)
    case "$MACHINE" in
      i?86|x86_64)
        LONG_BIT=$(getconf LONG_BIT)
        # We know we are on x86 but we need to use getconf to determine
        # bittage of the userspace install (e.g. when running 32-bit userspace
        # on x86_64 kernel)
        exec "${THIS_DIR}/linux${LONG_BIT}/gn" "$@";;
      *)
        echo Unknown architecture \($MACHINE\) -- unable to run gn.
        print_help
        exit 1;;
    esac
    ;;
  Darwin)    exec "${THIS_DIR}/mac/gn" "$@";;
  CYGWIN*)   exec cmd.exe /c $(cygpath -t windows $0).exe "$@";;
  MINGW*)    cmd.exe //c $0.exe "$@";;
  *)         echo "Unsupported OS ${OS}"
             print_help
             exit 1;;
esac
